SELECT * FROM (
SELECT SUBSTR( (PHONE_NUMBER), 1 , 3  ) AS vi_o, COUNT(EMPLOYEE_ID) AS vi_t 
FROM EMPLOYEES
GROUP BY SUBSTR( (PHONE_NUMBER), 1 , 3  )
)
PIVOT
(
SUM (vi_t) FOR vi_o IN(515,590,603,'011',650)
)pivot;
